# ONLY REALLY WORKS ON LINUX, YOU'LL PROBABLY HAVE TO MANUALLY INSTALL THE REQUIREMENTS ON ANYTHNIG ELSE 

# RUN THIS SCRIPT FROM THE 'SETUP' DIRECTORY OR ELSE EVERYTHING WILL BE WRONG 
bash setupPythonPrereqs.bash 
bash setupJS.bash